-- Idempotent: add English (en) facts and questions. Re-runnable via ON CONFLICT DO NOTHING.
BEGIN;

-- EN facts
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_ticket_validity','ticket_validity','en','18 months','https://www.stib-mivb.be/accueil/support-client/tarifs-et-titres-de-transport','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_connection_window','connection_window','en','60 minutes','https://www.stib-mivb.be/accueil/support-client/tarifs-et-titres-de-transport','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_day_cap_eur','day_cap_eur','en','8.50 EUR','https://www.stib-mivb.be/accueil/support-client/tarifs-et-titres-de-transport','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_mobib_validity','mobib_validity','en','5 years','https://www.stib-mivb.be/acheter/tous-vos-deplacements-avec-la-carte-mobib','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_mobib_card_price','mobib_card_price','en','6 EUR','https://www.stib-mivb.be/acheter/tous-vos-deplacements-avec-la-carte-mobib','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_mobib_capacity','mobib_capacity','en','8 tickets','https://www.stib-mivb.be/acheter/tous-vos-deplacements-avec-la-carte-mobib','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_fine_first','fine_first','en','107 EUR','https://www.stib-mivb.be/accueil/support-client/amende-et-infractions-','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_fine_second_24m','fine_second_24m','en','214 EUR','https://www.stib-mivb.be/accueil/support-client/amende-et-infractions-','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_fine_misuse_mobib','fine_misuse_mobib','en','408 EUR','https://www.stib-mivb.be/accueil/support-client/amende-et-infractions-','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_fine_unvalidated','fine_unvalidated','en','10 EUR','https://www.stib-mivb.be/accueil/support-client/amende-et-infractions-','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_duplicate_card_cost','duplicate_card_cost','en','10 EUR','https://www.stib-mivb.be/accueil/support-client/objets-perdus','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_duplicate_delivery_days','duplicate_delivery_days','en','5 working days','https://www.stib-mivb.be/accueil/support-client/objets-perdus','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_school_ticket_price','school_ticket_price','en','12 EUR/year','https://www.stib-mivb.be/acheter/abonnements-scolaires-pour-eleves-et-etudiants','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_airport_fare','airport_fare','en','7.90 EUR','https://www.stib-mivb.be/acheter/votre-carte-bancaire-est-votre-ticket','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_digital_1journey','digital_1journey','en','2.70 EUR','https://www.stib-mivb.be/acheter/le-ticket-digital','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO facts (id,key,lang,value,source_ref,last_verified,linked_fact_id,topic) VALUES ('fact_en_senior_reduced_age','senior_reduced_age','en','65 years or older','https://www.stib-mivb.be/accueil/support-client/tarifs-preferentiels','2026-08-15',NULL,NULL) ON CONFLICT (id) DO NOTHING;

-- EN questions (expected_fact_keys stored as JSON string, matching the seeder)
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_001','stib_transport_v1','en','fares','deadline','How long does a STIB transport ticket remain valid after purchase?','["ticket_validity"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_002','stib_transport_v1','en','fares','general','For how long can I make connections with the same STIB ticket?','["connection_window"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_003','stib_transport_v1','en','fares','fees','What is the maximum amount charged per day with contactless payment on STIB?','["day_cap_eur"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_004','stib_transport_v1','en','mobib','general','How long is a MOBIB card valid?','["mobib_validity"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_005','stib_transport_v1','en','mobib','fees','How much does a reloadable MOBIB card cost?','["mobib_card_price"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_006','stib_transport_v1','en','mobib','general','How many transport tickets can be loaded onto a MOBIB card?','["mobib_capacity"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_007','stib_transport_v1','en','fines','fees','What is the STIB fine for not having a valid transport ticket?','["fine_first"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_008','stib_transport_v1','en','fines','fees','What is the amount of a second STIB fine received within 24 months?','["fine_second_24m"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_009','stib_transport_v1','en','fines','fees','What fine applies if I use someone else''s MOBIB card?','["fine_misuse_mobib"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_010','stib_transport_v1','en','fines','fees','What is the fine if I have a valid season ticket but did not validate it?','["fine_unvalidated"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_011','stib_transport_v1','en','lost','fees','How much does a duplicate of a personal MOBIB card cost?','["duplicate_card_cost"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_012','stib_transport_v1','en','lost','deadline','Within how many days is a duplicate card ordered online delivered by post?','["duplicate_delivery_days"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_013','stib_transport_v1','en','school','fees','How much does the STIB school season ticket cost per year?','["school_ticket_price"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_014','stib_transport_v1','en','fares','fees','What special fare applies from Brussels Airport (Airport City)?','["airport_fare"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_015','stib_transport_v1','en','fares','fees','How much does a digital Brupass ticket for one journey cost?','["digital_1journey"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO questions (id,question_set_id,lang,topic,risk_tag,text,expected_fact_keys) VALUES ('q_en_016','stib_transport_v1','en','eligibility','eligibility','From what age are you entitled to a reduced senior fare on STIB?','["senior_reduced_age"]') ON CONFLICT (id) DO NOTHING;

COMMIT;